version: "3.9"

services:
  db:
    image: postgres:15.4-alpine3.18
    hostname: db
    ports:
      - "5052:5052"
    environment:  
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "smartamm"
      PGDATA: /var/lib/postgresql/data/smartamm/
    restart: unless-stopped
    command: -p 5052
    volumes:
      - pg-data:/var/lib/postgresql/data
    


  server:
    image: pinakipatra/smartamm-server:latest
    build: 
      context: srv
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "4004:4004"

  client:
    image: pinakipatra/smartamm-client:latest
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pinaki.patra@t-systems.com
      PGADMIN_DEFAULT_PASSWORD: Sap#2016
    volumes:
      - pgadmin-data:/var/lib/pgadmin4/storage
    depends_on:
      - db

volumes:
  pg-data:
  pgadmin-data:
