version: "3.9"

services:
  db:
    image: postgres:latest
    hostname: db
    ports:
      - "5432:5432"
    environment:  
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "smartamm"
    restart: unless-stopped
    networks:
      - smartamm-tier
    command: -p 5432
  server:
    image: smartamm-server:latest
    build: 
      context: srv
      dockerfile: Dockerfile
    hostname: server
    depends_on:
      - db
    ports:
      - "4004:4004"
    environment:
      DATABASE_URL: "postgresql://postgres:123@db:5432/smartamm?schema=public"
    networks:
      - smartamm-tier
  client:
    image: smartamm-client:latest
    build:
      context: app
      dockerfile: Dockerfile
    hostname: client  
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - smartamm-tier
networks:
  smartamm-tier:
    driver: bridge