@route = http://127.0.0.1:4004

### Get Chart Data Box Plot
POST  {{route}}/getChartData
Authorization: Basic 75F1F65661AA8EF556B3C51DF9F8F:BC31EAB8C7FB57B296B4C5CE97572
Content-Type: application/json

{
  "title": "My New Chart",
  "type": "chart",
  "options": {
    "metrics": [],
    "chartType": "BoxPlot",
    "config": {
      "isStack": true,
      "agg":{
        "age":"statisticalSummary"
      },
      "projectID":"917a1c2a-e21a-4ff4-8339-720039f1199d",
      "xField": "Priority",
      "yField": "Category",
      "seriesField": [],
      "measure":["age"],
      "dimension":["sport"],
      "series":[]
    }
  }
}


### Get Chart Data Box Plot
POST  {{route}}/getChartData
Authorization: Basic 75F1F65661AA8EF556B3C51DF9F8F:BC31EAB8C7FB57B296B4C5CE97572
Content-Type: application/json

{
"title":"MyNewChart",
"type":"chart",
"options":{
"metrics":[],
"chartType":"Bar",
"config":{
"isStack":true,
"agg":{
"count":"Impact"
},
"projectID":"ed136cad-31b1-4b0e-9255-f96ee73bc164",
"xField":"Priority",
"yField":"Category",
"seriesField":"sport",
"dimension":["Contact Media"],
"measure":["Impact"],
"series":["DAY_CC"]
}
}
}


###Get Chart Data Bigram Word Cloud
POST {{route}}/getChartData
Authorization: Basic 75F1F65661AA8EF556B3C51DF9F8F:BC31EAB8C7FB57B296B4C5CE97572
Content-Type: application/json

{
  "title": "My New Chart",
  "type": "chart",
  "options": {
    "metrics": [],
    "chartType": "Bigram", 
     "config": {
      "dimension": ["Short Description"], 
      "stopWords": "custom,stop,words",
      "projectID": "04b704db-92d2-49e0-a25a-b6e72a4d9cef"
    }
  }
}


###Get Chart Data  Word Cloud
POST {{route}}/getChartData
Authorization: Basic 75F1F65661AA8EF556B3C51DF9F8F:BC31EAB8C7FB57B296B4C5CE97572
Content-Type: application/json

{
  "title": "My New Chart",
  "type": "chart",
  "options": {
    "metrics": [],
    "chartType": "WordCloud", 
     "config": {
      "dimension": ["Short Description"], 
      "stopWords": "custom,stop,words",
      "projectID": "04b704db-92d2-49e0-a25a-b6e72a4d9cef"
    }
  }
}

# {
#   "title": "My New Chart",
#   "type": "chart",
#   "options": {
#     "metrics": [],
#     "chartType": "Pie",
#     "config": {
#       "appendPadding": 10,
#       "projectID":"377af7e3-5356-4a2a-a840-7a36e740f623",
#       "angleField": "Urgency",
#       "colorField": "Urgency",
#       "radius": 0.9,
#       "aggregationFunction":"COUNT"
#     }
#   }
# }