@route = http://127.0.0.1:4004

### Get Chart Data
POST  {{route}}/getChartData
Content-Type: application/json

{
  "title": "My New Chart",
  "type": "chart",
  "options": {
    "metrics": [],
    "chartType": "WordCloud",
    "config": {
      "isStack": true,
      "agg":{
      },
      "projectID":"0622c0ab-9996-4e23-a3e3-31f1524cf79a",
      "xField": "Priority",
      "yField": "Category",
      "seriesField": "Country",
      "dimension":["Assigned to Group","Contact Media"],
      "languages":["eng","swe"],
      "customWords":["100","sap"],
      "measure":[],
      "series":[]
    }
  }
}




# {
#   "title": "My New Chart",
#   "type": "chart",
#   "options": {
#     "metrics": [],
#     "chartType": "Pie",
#     "config": {
#       "appendPadding": 10,
#       "projectID":"377af7e3-5356-4a2a-a840-7a36e740f623",
#       "angleField": "Urgency",
#       "colorField": "Urgency",
#       "radius": 0.9,
#       "aggregationFunction":"COUNT"
#     }
#   }
# }