@route = http://127.0.0.1:4004

### Get Projects
GET  {{route}}/getProjects


### Get Project Details
GET  {{route}}/getProjectDetails/df57c50c-d4e6-4676-9b13-f3a3e6cd48ed

### Delete Project
GET  {{route}}/deleteProject/df57c50c-d4e6-4676-9b13-f3a3e6cd48ed


### Create Project
POST  {{route}}/createProject
Content-Type: application/json

{
    "name": "Analysis", 
    "data":  [
  {
    "Incident ID": "IM19004815",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO S&P WW SAP AUTHORIZATION",
    "Impact": "4",
    "Urgency": "1",
    "Priority": "2",
    "Open Time": "07.01.2019  01:30:21 ",
    "Opened by": "CORP INFRA-CS AP IT SERVICE DESK",
    "Resolved Time": "09.01.2019  07:54:21 ",
    "Resolved by": "AUTO S&P WW SAP AUTHORIZATION",
    "Classification 1": "HORIZATION",
    "Closed Time": "23.01.2019  08:05:09 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "A3P/100",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Asia & Pacific",
    "Country": "China",
    "City": "Wuhu",
    "Short Description": "SAP subaccounts - change main user",
    "Issue Type": "Authorization: Access related",
    "Language": "English",
    "Day": "Monday",
    "MTTR": "2.27",
    "Hour": "8"
  },
  {
    "Incident ID": "IM19006525",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO S&P WW SAP AUTHORIZATION",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "07.01.2019  07:39:56 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "07.01.2019  21:00:46 ",
    "Resolved by": "AUTO S&P WW SAP AUTHORIZATION",
    "Classification 1": "HORIZATION",
    "Closed Time": "21.01.2019  21:51:57 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "EP1/111",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Ulm",
    "Short Description": "Please reset my Password for EP1",
    "Issue Type": "Authorization: Password related",
    "Language": "English",
    "Day": "Monday",
    "MTTR": "0.56",
    "Hour": "8"
  },
  {
    "Incident ID": "IM18990868",
    "Status": "Closed",
    "Contact Media": "Phone",
    "Assigned to Group": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "02.01.2019  08:52:15 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved by": "",
    "Classification 1": "",
    "Closed Time": "02.01.2019  09:02:50 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "NZP/010",
    "ProductType": "BC - Basis",
    "Module": "SAP BASIS",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Dortmund",
    "Short Description": "SAP NZP opening issue",
    "Language": "English",
    "Day": "Wednesday",
    "MTTR": "0.8",
    "Hour": "8"
  },
  {
    "Incident ID": "IM18990912",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO SAP AP CIP 100 SD",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "02.01.2019  08:57:33 ",
    "Opened by": "CORP INFRA-CS AP IT SERVICE DESK",
    "Resolved Time": "04.02.2019  03:09:07 ",
    "Resolved by": "AUTO SAP AP CIP 100 SD",
    "Classification 1": "CIP 100 SD",
    "Closed Time": "04.02.2019  05:24:11 ",
    "Closed by": "",
    "Category": "General Information (IN)",
    "SubCategory": "Information",
    "ProductType": "Location Info",
    "ProblemType": "Request",
    "Region": "Asia & Pacific",
    "Country": "India",
    "City": "Bangalore",
    "Short Description": "Auto generated despatch details are not coming through mail",
    "Language": "English",
    "MTTR": "32.76",
    "Hour": "8"
  },
  {
    "Incident ID": "IM19006540",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO S&P WW SAP AUTHORIZATION",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "07.01.2019  07:40:51 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "08.01.2019  09:30:13 ",
    "Resolved by": "AUTO S&P WW SAP AUTHORIZATION",
    "Classification 1": "HORIZATION",
    "Closed Time": "22.01.2019  10:25:23 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "CBW/100",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Babenhausen",
    "Short Description": "Password Reset for CBW 100",
    "Issue Type": "Authorization: Password related",
    "Language": "English",
    "Day": "Monday",
    "MTTR": "1.08",
    "Hour": "9"
  },
  {
    "Incident ID": "IM19007372",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO S&P WW SAP AUTHORIZATION",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "07.01.2019  08:41:26 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "10.01.2019  12:58:09 ",
    "Resolved by": "AUTO S&P WW SAP AUTHORIZATION",
    "Classification 1": "HORIZATION",
    "Closed Time": "24.01.2019  13:50:50 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "NZP/010",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Bebra",
    "Short Description": "Kennwortvergabe NZI Testsystem",
    "Issue Type": "Authorization: Password related",
    "Language": "German",
    "Day": "Monday",
    "MTTR": "3.18",
    "Hour": "9"
  },
  {
    "Incident ID": "IM19007707",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "07.01.2019  09:06:56 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "08.01.2019  11:30:19 ",
    "Resolved by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Classification 1": "RVICE DESK",
    "Closed Time": "09.01.2019  07:48:57 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "CBW/100",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Babenhausen",
    "Short Description": "Access to SAP System CBW SAP-Client is not possible",
    "Issue Type": "Authorization: Access related",
    "Language": "English",
    "Day": "Monday",
    "MTTR": "1.10",
    "Hour": "9"
  },
  {
    "Incident ID": "IM19007887",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO S&P WW SAP AUTHORIZATION",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "07.01.2019  09:18:55 ",
    "Opened by": "CORP INFRA-CS EU3 IT SERVICE DESK",
    "Resolved by": "",
    "Classification 1": "",
    "Closed Time": "10.01.2019  07:13:13 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "AVP/020",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Spain",
    "City": "Rubi",
    "Short Description": "Ha caducado mi cuenta de SAP",
    "Issue Type": "Authorization",
    "Language": "English",
    "Day": "Monday",
    "MTTR": "7.8",
    "Hour": "9"
  },
  {
    "Incident ID": "IM18991005",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "CORP INFRA-CS WW SYSTEM OPERATIONS IAM",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "02.01.2019  09:07:37 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "14.01.2019  03:42:25 ",
    "Resolved by": "CORP INFRA-CS WW SYSTEM OPERATIONS IAM",
    "Classification 1": "ATIONS IAM",
    "Closed Time": "28.01.2019  04:07:52 ",
    "Closed by": "",
    "Category": "IT Management (IT)",
    "SubCategory": "Service Management (ItSM)",
    "ProductType": "Identity and Access Management (IAM)",
    "Module": "Access",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Regensburg",
    "Short Description": "Bitte Personalnummer 1181182 mit uia66956 verknüpfen",
    "Language": "German",
    "MTTR": "11.77",
    "Hour": "9"
  },
  {
    "Incident ID": "IM18991040",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO LOC EU1 RB LOCAL SERVICES BP",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "02.01.2019  09:12:45 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "02.01.2019  13:11:56 ",
    "Resolved by": "AUTO LOC EU1 RB LOCAL SERVICES BP",
    "Classification 1": "ERVICES BP",
    "Closed Time": "16.01.2019  13:14:20 ",
    "Closed by": "",
    "Category": "Communication (CO)",
    "SubCategory": "Notes Application",
    "ProductType": "ePCIS (C&S)",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Regensburg",
    "Language": "English",
    "MTTR": "0.17",
    "Hour": "9"
  },
  {
    "Incident ID": "IM19008024",
    "Status": "Closed",
    "Contact Media": "Phone",
    "Assigned to Group": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "07.01.2019  09:29:40 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "08.01.2019  11:23:59 ",
    "Resolved by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Classification 1": "RVICE DESK",
    "Closed Time": "22.01.2019  11:41:00 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "EP1/111",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Berlin",
    "Short Description": "EP1-111 - Transaction missing.",
    "Issue Type": "Authorization",
    "Language": "German",
    "Day": "Monday",
    "MTTR": "1.08",
    "Hour": "9"
  },
  {
    "Incident ID": "IM19008214",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO S&P WW SAP AUTHORIZATION",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "07.01.2019  09:44:06 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "15.01.2019  14:20:05 ",
    "Resolved by": "AUTO S&P WW SAP AUTHORIZATION",
    "Classification 1": "HORIZATION",
    "Closed Time": "29.01.2019  14:43:44 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "CBW/100",
    "ProductType": "Authorization",
    "Module": "Authorization",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Germany",
    "City": "Frankfurt am Main",
    "Short Description": "GlobalPS Name Issue",
    "Issue Type": "Authorization",
    "Language": "English",
    "Day": "Monday",
    "MTTR": "8.19",
    "Hour": "9"
  },
  {
    "Incident ID": "IM18991119",
    "Status": "Closed",
    "Contact Media": "Employee Self Service",
    "Assigned to Group": "AUTO SAP EU NTP 015 PP",
    "Impact": "4",
    "Urgency": "3",
    "Priority": "3",
    "Open Time": "02.01.2019  09:20:43 ",
    "Opened by": "CORP INFRA-CS EU1&2 IT SERVICE DESK",
    "Resolved Time": "02.01.2019  09:48:05 ",
    "Resolved by": "AUTO SAP EU NTP 015 PP",
    "Classification 1": "NTP 015 PP",
    "Closed Time": "16.01.2019  10:01:28 ",
    "Closed by": "",
    "Category": "SAP",
    "SubCategory": "NTP/015",
    "ProductType": "1st Level",
    "Module": "L1",
    "ProblemType": "Failure",
    "Region": "Europe",
    "Country": "Czech Republic",
    "City": "Brandys nad Labem",
    "Short Description": "odesilani odvolavek",
    "Language": "Czech",
    "Day": "Wednesday",
    "MTTR": "0.02",
    "Hour": "9"
  }],
    "description": "Analyse and transform",
    "configData" : [
        {
            "colName": "Incident ID",
            "previewValues": [
            "IM18988797",
            "IM18990182",
            "IM18990968",
            "IM18991481",
            "IM18992919"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Status",
            "previewValues": [
            "Closed",
            "Closed",
            "Closed",
            "Closed",
            "Closed"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Contact Media",
            "previewValues": [
            "Interface",
            "Employee Self Service",
            "Employee Self Service",
            "Employee Self Service",
            "Employee Self Service"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Assigned to Group",
            "previewValues": [
            "AUTO S&P WW SAP AUTHORIZATION",
            "CORP INFRA-CS AP IT SERVICE DESK",
            "AUTO S&P WW SAP AUTHORIZATION",
            "AUTO S&P WW SAP AUTHORIZATION",
            "AUTO S&P WW SAP AUTHORIZATION"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Impact",
            "previewValues": [
            "4",
            "4",
            "4",
            "4",
            "4"
            ],
            "enabled": true,
            "dataType": "Number"
        },
        {
            "colName": "Urgency",
            "previewValues": [
            "2",
            "3",
            "3",
            "3",
            "3"
            ],
            "enabled": true,
            "dataType": "Number"
        },
        {
            "colName": "Priority",
            "previewValues": [
            "3",
            "3",
            "3",
            "3",
            "3"
            ],
            "enabled": true,
            "dataType": "Number"
        },
        {
            "colName": "Open Time",
            "previewValues": [
            "01.01.2019  13:17:32 ",
            "02.01.2019  07:23:40 ",
            "02.01.2019  09:03:06 ",
            "02.01.2019  09:46:52 ",
            "02.01.2019  14:08:03 "
            ],
            "enabled": true,
            "dataType": "Date-Time"
        },
        {
            "colName": "Opened by",
            "previewValues": [
            "CORP INFRA-CS EU1&2 IT SERVICE DESK",
            "CORP INFRA-CS AP IT SERVICE DESK",
            "CORP INFRA-CS EU1&2 IT SERVICE DESK",
            "CORP INFRA-CS EU1&2 IT SERVICE DESK",
            "CORP INFRA-CS EU1&2 IT SERVICE DESK"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Resolved Time",
            "previewValues": [
            "03.01.2019  10:40:31 ",
            "03.01.2019  05:28:35 ",
            "04.01.2019  08:11:40 ",
            "15.02.2019  13:26:44 ",
            "02.01.2019  21:02:11 "
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Resolved by",
            "previewValues": [
            "AUTO S&P WW SAP AUTHORIZATION",
            "CORP INFRA-CS AP IT SERVICE DESK",
            "AUTO S&P WW SAP AUTHORIZATION",
            "AUTO S&P WW SAP AUTHORIZATION",
            "AUTO S&P WW SAP AUTHORIZATION"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Classification 1",
            "previewValues": [
            "HORIZATION",
            "RVICE DESK",
            "HORIZATION",
            "HORIZATION",
            "HORIZATION"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Closed Time",
            "previewValues": [
            "04.01.2019  07:22:32 ",
            "17.01.2019  05:56:01 ",
            "18.01.2019  08:19:37 ",
            "21.02.2019  12:08:17 ",
            "16.01.2019  21:46:43 "
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Closed by",
            "previewValues": [
            "<blank>",
            "<blank>",
            "<blank>",
            "<blank>",
            "<blank>"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Category",
            "previewValues": [
            "SAP",
            "SAP",
            "SAP",
            "SAP",
            "SAP"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "SubCategory",
            "previewValues": [
            "NZP/010",
            "CBW/100",
            "EP1/111",
            "CSE/600",
            "CSE/600"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "ProductType",
            "previewValues": [
            "Authorization",
            "Authorization",
            "Authorization",
            "Authorization",
            "Authorization"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Module",
            "previewValues": [
            "Authorization",
            "Authorization",
            "Authorization",
            "Authorization",
            "Authorization"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "ProblemType",
            "previewValues": [
            "Failure",
            "Failure",
            "Failure",
            "Failure",
            "Failure"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Region",
            "previewValues": [
            "Europe",
            "Asia & Pacific",
            "Europe",
            "Europe",
            "Europe"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Country",
            "previewValues": [
            "Germany",
            "China",
            "Germany",
            "Czech Republic",
            "Germany"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "City",
            "previewValues": [
            "Bebra",
            "Shanghai",
            "Schwalbach",
            "Ostrava",
            "Babenhausen"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Short Description",
            "previewValues": [
            "* Firma in den User Paramtern",
            "JD: Global PS password expired",
            "Bitte Kennwort zurück setzen.",
            "Blocked access to SAP CSE-PRD-AUTO",
            "Lexpro Password reset needed"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Issue Type",
            "previewValues": [
            "Authorization: user related",
            "Authorization: Password related",
            "Authorization: Password related",
            "Authorization: Access related",
            "Authorization: Password related"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Language",
            "previewValues": [
            "German",
            "English",
            "German",
            "English",
            "English"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "Day",
            "previewValues": [
            "Tuesday",
            "Wednesday",
            "Wednesday",
            "Wednesday",
            "Wednesday"
            ],
            "enabled": true,
            "dataType": "Text"
        },
        {
            "colName": "MTTR",
            "previewValues": [
            "1.89",
            "0.92",
            "1.96",
            "44.15",
            "0.29"
            ],
            "enabled": true,
            "dataType": "Number"
        },
        {
            "colName": "Hour",
            "previewValues": [
            "10",
            "13",
            "14",
            "14",
            "20"
            ],
            "enabled": true,
            "dataType": "Number"
        }
        ],
    "modifiedBy":"postgres"
}