name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build the UI Docker image
        run: docker build -t pinakipatra/smartamm-client ./app
      - name: Build the Server Docker image
        run: docker build -t pinakipatra/smartamm-server ./srv
      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: pinakipatra
          password: Pinaki@2022
      - name: Push the  client Docker image
        run: docker push pinakipatra/smartamm-client
      - name: Push the server Docker image
        run: docker push pinakipatra/smartamm-server
