name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        run: docker build -t pinakipatra/smartamm-client ./app
      - name: Push the Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: pinakipatra
          password: Pinaki@2022
      - name: Push the Docker image
        run: docker push pinakipatra/smartamm-client
